from ChatNGameWebsite.user.views import RegisterViewSet
from django.urls import path
from rest_framework import routers
from views import LoginViewSet, RegisterViewSet

#initializing the router and adding the nessesary viewsets to it
router = routers.SimpleRouter()
router.register('login', LoginViewSet)
router.register('register', RegisterViewSet)

#giving the urlpatterns the urls generated by the router
urlpatterns = router.urls